M48
; DRILL file {KiCad 8.0.6} date 2024-12-08T12:16:13-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-08T12:16:13-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X1.3Y-2.3
X1.5Y-2.3
T2
X1.6898Y-2.3028
X1.8898Y-2.3028
T3
X1.6795Y-2.2
X1.9Y-2.2
T4
X0.9055Y-2.0079
X0.9055Y-5.6693
X4.5669Y-2.0079
X4.5669Y-5.6693
M30
